name: PHP Composer

on:
  push:
    branches: [ "main", dev ]
  pull_request:
    branches: [ "main", dev  ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: (Env) Fix .env for production
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.PROD_ENV }}" > .env

    - name: (Env) Fix .env for development
      if: github.ref == 'refs/heads/dev'
      run: |
        echo "${{ secrets.DEV_ENV }}" > .env

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # - name: Set up PHP
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: 8.2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPUnit test suite
      run: composer test

    - name: (Deploy prod) Copy file via ssh event.fpv.jp
      if: github.ref == 'refs/heads/main'
      uses: appleboy/scp-action@v0.1.4
      with:
        host: v2008.coreserver.jp
        username: fpv
        port: 22
        key: ${{ secrets.KEY }}
        source: .env,bootstrap.php,settings.php,private_html/,src/,vendor/
        target: /home/fpv/domains/event.fpv.jp/
        overwrite: true

    - name: (Deploy dev) Copy file via ssh fpv.v2008.coreserver.jp
      if: github.ref == 'refs/heads/dev'
      uses: appleboy/scp-action@v0.1.4
      with:
        host: v2008.coreserver.jp
        username: fpv
        port: 22
        key: ${{ secrets.KEY }}
        source: .env,bootstrap.php,settings.php,private_html/,src/,vendor/
        target: /home/fpv/domains/fpv.v2008.coreserver.jp/
        overwrite: true

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
